netboot: Improve error reporting in mk-s390image
If an input file is not readable return a proper error message indicating
this.

Before:

$ mk-s390image /var/lib/libvirt/images/hades/vmlinux-s390x out.img
mk-s390image: Unrecognized file format for /var/lib/libvirt/images/hades/vmlinux-s390x

After:

$ mk-s390image /var/lib/libvirt/images/hades/vmlinux-s390x out.img
mk-s390image: File /var/lib/libvirt/images/hades/vmlinux-s390x cannot be read, no read permission

Reviewed-by: Jan Höppner <hoeppner@linux.ibm.com>
Signed-off-by: Marc Hartmayer <mhartmay@linux.ibm.com>
Signed-off-by: Jan Höppner <hoeppner@linux.ibm.com>

diff --git a/netboot/mk-s390image b/netboot/mk-s390image
--- a/netboot/mk-s390image
+++ b/netboot/mk-s390image
@@ -123,6 +123,11 @@ dobuild()
 		echo "$cmd: File $i not found" >&2
 		return 1
 	fi
+	if [ ! -r "$i" ]
+	then
+		echo "$cmd: File $i cannot be read, no read permission" >&2
+		return 1
+	fi
 	done
 	if ! file -b -- "$(readlink -f -- "$kernel")" | grep "Linux S390" > /dev/null
 	then
